
/*
  # Seed Coral Species Database
*/

INSERT INTO coral_species (coral_group, genus, species, common_name, rarity_tier, care_difficulty, light_requirement, flow_requirement) VALUES
('SPS', 'Acropora', 'millepora', 'Millepora Acropora', 'Uncommon', 'Advanced', 'High', 'High'),
('SPS', 'Acropora', 'tortuosa', 'Tortuosa Acropora', 'Rare', 'Advanced', 'High', 'High'),
('SPS', 'Acropora', 'valida', 'Valida Acropora', 'Uncommon', 'Advanced', 'High', 'High'),
('SPS', 'Acropora', 'lokani', 'Lokani Acropora', 'Rare', 'Expert', 'High', 'High'),
('SPS', 'Acropora', 'tenuis', 'Tenuis Acropora', 'Uncommon', 'Advanced', 'High', 'High'),
('SPS', 'Acropora', 'caroliniana', 'Caroliniana Acropora', 'Rare', 'Advanced', 'High', 'High'),
('SPS', 'Acropora', 'hyacinthus', 'Table Acropora', 'Rare', 'Expert', 'High', 'High'),
('SPS', 'Acropora', 'nana', 'Nana Acropora', 'Uncommon', 'Advanced', 'High', 'High'),
('SPS', 'Acropora', 'secale', 'Secale Acropora', 'Rare', 'Expert', 'High', 'High'),
('SPS', 'Acropora', 'microclados', 'Microclados Acropora', 'Ultra Rare', 'Expert', 'High', 'High'),
('SPS', 'Montipora', 'capricornis', 'Plating Montipora', 'Common', 'Beginner', 'Medium', 'Medium'),
('SPS', 'Montipora', 'undata', 'Wavy Montipora', 'Uncommon', 'Intermediate', 'Medium', 'Medium'),
('SPS', 'Montipora', 'confusa', 'Confusa Montipora', 'Uncommon', 'Intermediate', 'Medium', 'Medium'),
('SPS', 'Montipora', 'digitata', 'Branching Montipora', 'Common', 'Beginner', 'Medium', 'Medium'),
('SPS', 'Montipora', 'tuberculosa', 'Tuberculosa Montipora', 'Uncommon', 'Intermediate', 'Medium', 'Medium'),
('SPS', 'Montipora', 'spumosa', 'Spumosa Montipora', 'Rare', 'Advanced', 'Medium', 'Medium'),
('SPS', 'Seriatopora', 'hystrix', 'Bird''s Nest Coral', 'Common', 'Intermediate', 'Medium', 'High'),
('SPS', 'Seriatopora', 'caliendrum', 'Caliendrum Bird''s Nest', 'Uncommon', 'Intermediate', 'Medium', 'High'),
('SPS', 'Seriatopora', 'guttatus', 'Guttatus Bird''s Nest', 'Rare', 'Advanced', 'Medium', 'High'),
('SPS', 'Stylophora', 'pistillata', 'Stylophora', 'Common', 'Beginner', 'Medium', 'Medium'),
('SPS', 'Stylophora', 'mamillata', 'Mamillata Stylophora', 'Uncommon', 'Intermediate', 'Medium', 'Medium'),
('SPS', 'Stylophora', 'danae', 'Danae Stylophora', 'Rare', 'Advanced', 'High', 'Medium'),
('SPS', 'Pocillopora', 'damicornis', 'Cauliflower Coral', 'Common', 'Beginner', 'Medium', 'Medium'),
('SPS', 'Pocillopora', 'verrucosa', 'Verrucose Pocillopora', 'Common', 'Beginner', 'Medium', 'Medium'),
('SPS', 'Pocillopora', 'eydouxi', 'Cauliflower Pocillopora', 'Uncommon', 'Intermediate', 'High', 'High'),
('SPS', 'Pocillopora', 'meandrina', 'Meandrina Pocillopora', 'Uncommon', 'Intermediate', 'High', 'High'),
('SPS', 'Porites', 'cylindrica', 'Finger Porites', 'Common', 'Intermediate', 'Medium', 'Medium'),
('SPS', 'Porites', 'lobata', 'Massive Porites', 'Common', 'Intermediate', 'Medium', 'Medium'),
('SPS', 'Porites', 'rus', 'Rus Porites', 'Uncommon', 'Advanced', 'High', 'Medium'),
('SPS', 'Pavona', 'cactus', 'Cactus Coral', 'Uncommon', 'Intermediate', 'Medium', 'Medium'),
('SPS', 'Pavona', 'decussata', 'Pavona', 'Common', 'Intermediate', 'Medium', 'Medium'),
('SPS', 'Pavona', 'frondifera', 'Frond Pavona', 'Uncommon', 'Intermediate', 'Medium', 'Medium'),
('SPS', 'Pavona', 'maldivensis', 'Maldives Pavona', 'Rare', 'Advanced', 'Medium', 'Medium'),
('SPS', 'Hydnophora', 'exesa', 'Horn Coral', 'Uncommon', 'Intermediate', 'Medium', 'Medium'),
('SPS', 'Hydnophora', 'rigida', 'Rigid Horn Coral', 'Uncommon', 'Intermediate', 'Medium', 'Medium'),
('SPS', 'Hydnophora', 'microconos', 'Microconos Horn Coral', 'Rare', 'Advanced', 'Medium', 'Medium'),
('SPS', 'Psammocora', 'contigua', 'Psammocora', 'Common', 'Beginner', 'Medium', 'Medium'),
('SPS', 'Psammocora', 'digitata', 'Finger Psammocora', 'Common', 'Beginner', 'Medium', 'Medium'),
('SPS', 'Psammocora', 'superficialis', 'Superficialis Psammocora', 'Uncommon', 'Intermediate', 'Medium', 'Medium'),
('SPS', 'Leptoseris', 'hawaiiensis', 'Hawaiian Leptoseris', 'Rare', 'Advanced', 'Low', 'Low'),
('SPS', 'Leptoseris', 'yabei', 'Yabei Leptoseris', 'Rare', 'Advanced', 'Low', 'Low'),
('SPS', 'Leptoseris', 'scabra', 'Scabra Leptoseris', 'Ultra Rare', 'Expert', 'Low', 'Low'),
('LPS', 'Acanthastrea', 'lordhowensis', 'Acan Lord', 'Uncommon', 'Intermediate', 'Medium', 'Low'),
('LPS', 'Acanthastrea', 'echinata', 'Echinata Acan', 'Rare', 'Intermediate', 'Medium', 'Low'),
('LPS', 'Acanthastrea', 'bowerbanki', 'Bowerbanki Acan', 'Uncommon', 'Intermediate', 'Medium', 'Low'),
('LPS', 'Acanthastrea', 'rotundoflora', 'Rotundoflora Acan', 'Rare', 'Intermediate', 'Medium', 'Low'),
('LPS', 'Blastomussa', 'wellsi', 'Blasto', 'Common', 'Beginner', 'Medium', 'Low'),
('LPS', 'Blastomussa', 'merleti', 'Merleti Blasto', 'Uncommon', 'Beginner', 'Medium', 'Low'),
('LPS', 'Trachyphyllia', 'geoffroyi', 'Open Brain Coral', 'Uncommon', 'Intermediate', 'Medium', 'Low'),
('LPS', 'Lobophyllia', 'hemprichii', 'Lobo Brain', 'Common', 'Beginner', 'Medium', 'Low'),
('LPS', 'Lobophyllia', 'corymbosa', 'Corymbosa Lobo', 'Uncommon', 'Beginner', 'Medium', 'Low'),
('LPS', 'Symphyllia', 'recta', 'Maze Brain', 'Uncommon', 'Intermediate', 'Medium', 'Low'),
('LPS', 'Symphyllia', 'wilsoni', 'Wilson''s Brain', 'Rare', 'Intermediate', 'Medium', 'Low'),
('LPS', 'Platygyra', 'sinensis', 'Maze Coral', 'Common', 'Beginner', 'Medium', 'Medium'),
('LPS', 'Favites', 'abdita', 'Moon Coral', 'Common', 'Beginner', 'Medium', 'Medium'),
('LPS', 'Favites', 'pentagona', 'War Coral', 'Common', 'Beginner', 'Medium', 'Medium'),
('LPS', 'Goniastrea', 'pectinata', 'Pineapple Coral', 'Common', 'Beginner', 'Medium', 'Medium'),
('LPS', 'Leptoria', 'phrygia', 'Grooved Brain Coral', 'Uncommon', 'Intermediate', 'Medium', 'Medium'),
('LPS', 'Caulastrea', 'furcata', 'Candy Cane Coral', 'Common', 'Beginner', 'Medium', 'Low'),
('LPS', 'Caulastrea', 'curvata', 'Curvata Candy Cane', 'Common', 'Beginner', 'Medium', 'Low'),
('LPS', 'Caulastrea', 'echinulata', 'Trumpet Coral', 'Uncommon', 'Beginner', 'Medium', 'Low'),
('LPS', 'Echinophyllia', 'aspera', 'Chalice Coral', 'Uncommon', 'Intermediate', 'Medium', 'Low'),
('LPS', 'Echinophyllia', 'orpheensis', 'Orpheensis Chalice', 'Rare', 'Intermediate', 'Medium', 'Low'),
('LPS', 'Oxypora', 'lacera', 'Oxypora Chalice', 'Rare', 'Intermediate', 'Medium', 'Low'),
('LPS', 'Oxypora', 'glabra', 'Glabra Chalice', 'Rare', 'Intermediate', 'Medium', 'Low'),
('LPS', 'Mycedium', 'elephantotus', 'Elephant Ear Chalice', 'Rare', 'Advanced', 'Medium', 'Low'),
('LPS', 'Duncanopsammia', 'axifuga', 'Duncan Coral', 'Common', 'Beginner', 'Medium', 'Low'),
('LPS', 'Catalaphyllia', 'jardinei', 'Elegance Coral', 'Uncommon', 'Advanced', 'Medium', 'Low'),
('LPS', 'Euphyllia', 'ancora', 'Hammer Coral', 'Common', 'Beginner', 'Medium', 'Medium'),
('LPS', 'Euphyllia', 'divisa', 'Frogspawn Coral', 'Common', 'Beginner', 'Medium', 'Medium'),
('LPS', 'Euphyllia', 'glabrescens', 'Torch Coral', 'Common', 'Beginner', 'Medium', 'Medium'),
('LPS', 'Euphyllia', 'cristata', 'Grape Coral', 'Uncommon', 'Intermediate', 'Medium', 'Medium'),
('LPS', 'Euphyllia', 'paradivisa', 'Branching Frogspawn', 'Uncommon', 'Intermediate', 'Medium', 'Medium'),
('LPS', 'Euphyllia', 'paraancora', 'Branching Hammer', 'Uncommon', 'Intermediate', 'Medium', 'Medium'),
('LPS', 'Favia', 'speciosa', 'Moon Coral', 'Common', 'Beginner', 'Medium', 'Medium'),
('LPS', 'Favia', 'pallida', 'Pallid Brain Coral', 'Common', 'Beginner', 'Medium', 'Medium'),
('LPS', 'Favia', 'matthaii', 'Matthaii Brain Coral', 'Uncommon', 'Intermediate', 'Medium', 'Medium'),
('LPS', 'Favites', 'complanata', 'Complanata Favites', 'Uncommon', 'Intermediate', 'Medium', 'Medium'),
('LPS', 'Favites', 'flexuosa', 'Flexuosa Favites', 'Uncommon', 'Intermediate', 'Medium', 'Medium'),
('LPS', 'Goniopora', 'lobata', 'Flowerpot Coral', 'Uncommon', 'Advanced', 'Medium', 'Low'),
('LPS', 'Goniopora', 'columna', 'Column Flowerpot', 'Uncommon', 'Advanced', 'Medium', 'Low'),
('LPS', 'Goniopora', 'djiboutiensis', 'Djibouti Flowerpot', 'Rare', 'Advanced', 'Medium', 'Low'),
('LPS', 'Alveopora', 'allingi', 'Alling''s Alveopora', 'Uncommon', 'Advanced', 'Medium', 'Low'),
('LPS', 'Alveopora', 'fenestrata', 'Fenestrate Alveopora', 'Uncommon', 'Advanced', 'Medium', 'Low'),
('LPS', 'Micromussa', 'lordhowensis', 'Micro Lord', 'Uncommon', 'Intermediate', 'Medium', 'Low'),
('LPS', 'Micromussa', 'amakusensis', 'Amakusensis Micromussa', 'Rare', 'Intermediate', 'Medium', 'Low'),
('LPS', 'Galaxea', 'fascicularis', 'Crystal Coral', 'Common', 'Intermediate', 'Medium', 'Medium'),
('LPS', 'Galaxea', 'astreata', 'Astreata Galaxea', 'Uncommon', 'Intermediate', 'Medium', 'Medium'),
('LPS', 'Heliofungia', 'actiniformis', 'Long Tentacle Plate', 'Uncommon', 'Intermediate', 'Medium', 'Low'),
('LPS', 'Fungia', 'scutaria', 'Plate Coral', 'Common', 'Beginner', 'Medium', 'Low'),
('LPS', 'Fungia', 'repanda', 'Repanda Plate Coral', 'Common', 'Beginner', 'Medium', 'Low'),
('LPS', 'Cycloseris', 'tenuis', 'Thin Plate Coral', 'Uncommon', 'Intermediate', 'Medium', 'Low'),
('LPS', 'Lithophyllon', 'undulatum', 'Undulate Plate Coral', 'Rare', 'Advanced', 'Medium', 'Low'),
('LPS', 'Montastraea', 'cavernosa', 'Great Star Coral', 'Common', 'Beginner', 'Medium', 'Medium'),
('LPS', 'Orbicella', 'faveolata', 'Mountainous Star Coral', 'Common', 'Beginner', 'Medium', 'Medium'),
('LPS', 'Meandrina', 'meandrites', 'Maze Coral', 'Uncommon', 'Intermediate', 'Medium', 'Medium'),
('LPS', 'Pectinia', 'alcicornis', 'Antler Pectinia', 'Rare', 'Advanced', 'Medium', 'Medium'),
('LPS', 'Pectinia', 'lactuca', 'Lettuce Coral', 'Rare', 'Advanced', 'Medium', 'Medium'),
('LPS', 'Pectinia', 'paeonia', 'Paeonia Pectinia', 'Ultra Rare', 'Expert', 'Medium', 'Medium'),
('LPS', 'Plerogyra', 'sinuosa', 'Bubble Coral', 'Common', 'Intermediate', 'Medium', 'Low'),
('LPS', 'Plerogyra', 'simplex', 'Pearl Bubble Coral', 'Uncommon', 'Intermediate', 'Medium', 'Low'),
('LPS', 'Physogyra', 'lichtensteini', 'Small Bubble Coral', 'Uncommon', 'Intermediate', 'Medium', 'Low'),
('LPS', 'Homophyllia', 'australis', 'Australian Scolymia', 'Rare', 'Intermediate', 'Medium', 'Low'),
('LPS', 'Scolymia', 'cubensis', 'Caribbean Scolymia', 'Rare', 'Intermediate', 'Medium', 'Low'),
('LPS', 'Scolymia', 'vitiensis', 'Vitiensis Scolymia', 'Ultra Rare', 'Advanced', 'Medium', 'Low'),
('Soft Coral', 'Sarcophyton', 'trocheliophorum', 'Toadstool Leather', 'Common', 'Beginner', 'Medium', 'Medium'),
('Soft Coral', 'Sarcophyton', 'elegans', 'Elegant Toadstool', 'Uncommon', 'Beginner', 'Medium', 'Medium'),
('Soft Coral', 'Sinularia', 'dura', 'Finger Leather', 'Common', 'Beginner', 'Medium', 'Medium'),
('Soft Coral', 'Sinularia', 'flexibilis', 'Flexible Finger Leather', 'Common', 'Beginner', 'Medium', 'Medium'),
('Soft Coral', 'Lobophytum', 'pauciflorum', 'Devil''s Hand Leather', 'Uncommon', 'Intermediate', 'Medium', 'Medium'),
('Soft Coral', 'Cladiella', 'sp.', 'Colt Coral', 'Common', 'Beginner', 'Medium', 'Medium'),
('Soft Coral', 'Zoanthus', 'sociatus', 'Zoanthid', 'Common', 'Beginner', 'Medium', 'Low'),
('Soft Coral', 'Zoanthus', 'sansibaricus', 'Sansibar Zoanthid', 'Common', 'Beginner', 'Medium', 'Low'),
('Soft Coral', 'Palythoa', 'grandis', 'Paly', 'Common', 'Beginner', 'Medium', 'Low'),
('Soft Coral', 'Palythoa', 'caribaeorum', 'Caribbean Paly', 'Common', 'Beginner', 'Medium', 'Low'),
('Soft Coral', 'Palythoa', 'toxica', 'Toxic Paly', 'Uncommon', 'Intermediate', 'Medium', 'Low'),
('Soft Coral', 'Ricordea', 'florida', 'Caribbean Ricordea', 'Uncommon', 'Beginner', 'Medium', 'Low'),
('Soft Coral', 'Ricordea', 'yuma', 'Indo-Pacific Ricordea', 'Uncommon', 'Beginner', 'Medium', 'Low'),
('Soft Coral', 'Rhodactis', 'indosinensis', 'Indo Rhodactis Mushroom', 'Common', 'Beginner', 'Low', 'Low'),
('Soft Coral', 'Rhodactis', 'osculifera', 'Bullseye Mushroom', 'Common', 'Beginner', 'Low', 'Low'),
('Soft Coral', 'Rhodactis', 'mussoides', 'Mushroom Coral', 'Common', 'Beginner', 'Low', 'Low'),
('Soft Coral', 'Rhodactis', 'howesii', 'Hairy Mushroom', 'Uncommon', 'Beginner', 'Low', 'Low'),
('Soft Coral', 'Discosoma', 'nummiforme', 'Discosoma Mushroom', 'Common', 'Beginner', 'Low', 'Low'),
('Soft Coral', 'Discosoma', 'sanctithomae', 'Mushroom Anemone', 'Common', 'Beginner', 'Low', 'Low'),
('Soft Coral', 'Discosoma', 'neglecta', 'Neglect Mushroom', 'Common', 'Beginner', 'Low', 'Low'),
('Soft Coral', 'Amplexidiscus', 'fenestrafer', 'Elephant Ear Mushroom', 'Uncommon', 'Intermediate', 'Medium', 'Low'),
('Soft Coral', 'Eunicea', 'sp.', 'Knobby Sea Rod', 'Uncommon', 'Intermediate', 'Medium', 'High'),
('Soft Coral', 'Plexaura', 'sp.', 'Sea Rod Gorgonian', 'Uncommon', 'Intermediate', 'Medium', 'High'),
('Soft Coral', 'Muricella', 'sp.', 'Sea Fan Gorgonian', 'Rare', 'Advanced', 'Low', 'High'),
('Soft Coral', 'Rumphella', 'sp.', 'Rumphella Sea Fan', 'Rare', 'Advanced', 'Medium', 'High'),
('Soft Coral', 'Melithaea', 'sp.', 'Colorful Sea Fan', 'Rare', 'Advanced', 'Low', 'High'),
('Soft Coral', 'Xenia', 'elongata', 'Pulsing Xenia', 'Common', 'Beginner', 'Medium', 'Medium'),
('Soft Coral', 'Xenia', 'umbellata', 'Umbrella Xenia', 'Common', 'Beginner', 'Medium', 'Medium'),
('Soft Coral', 'Heteroxenia', 'fuscescens', 'Pom Pom Xenia', 'Common', 'Beginner', 'Medium', 'Medium'),
('Soft Coral', 'Clavularia', 'viridis', 'Clove Polyp', 'Common', 'Beginner', 'Medium', 'Medium'),
('Soft Coral', 'Briareum', 'asbestinum', 'Star Polyp', 'Common', 'Beginner', 'Medium', 'Medium'),
('Soft Coral', 'Pachyclavularia', 'violacea', 'Green Star Polyp', 'Common', 'Beginner', 'Medium', 'Medium'),
('Soft Coral', 'Nephthea', 'sp.', 'Tree Coral', 'Uncommon', 'Intermediate', 'Medium', 'High'),
('Soft Coral', 'Litophyton', 'arboreum', 'Arboreum Tree Coral', 'Uncommon', 'Intermediate', 'Medium', 'High'),
('Soft Coral', 'Stereonephthya', 'sp.', 'Stereonephthya Tree Coral', 'Rare', 'Advanced', 'Medium', 'High')

ON CONFLICT (genus, species) DO NOTHING;
